[package]
name = "pof-tools"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.16"
egui = "0.16"
epi = "0.16"
glium = "0.31"
egui_glium = "0.16"
pof = { path = "pof" }
nalgebra-glm = "0.16.0"
native-dialog = "0.6.3"
crossbeam = "0.8.1"
image = "0.24.1"
