[package]
name = "pof-tools"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.16"
egui = "0.16"
epi = "0.16"
glium = "0.31"
egui_glium = "0.16"
pof = { path = "pof" }
nalgebra-glm = "0.16.0"
native-dialog = "0.6.3"
crossbeam = "0.8.1"
image = "0.24.1"
# for logging
simplelog = "0.11.2"
log = "0.4.14"
# for panic handling
backtrace = "0.3.64"
once_cell = "1.10"
# for display starup log date/time
chrono = "0.4.19"
